apiVersion: v1
kind: Service
metadata:
  name: frontend-v2
  labels:
    app: budzetownik
    tier: frontend
spec:
  type: LoadBalancer
  selector:
    app: budzetownik
    tier: frontend
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
