apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-custom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-custom
  template:
    metadata:
      labels:
        app: nginx-custom
    spec:
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html/index.html
          subPath: index.html
      volumes:
      - name: html
        configMap:
          name: custom-index
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-custom
spec:
  selector:
    app: nginx-custom
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30081
  type: NodePort
